-- Run this once in Supabase Dashboard > SQL Editor.
-- It creates the form table and permits anonymous inserts without exposing rows.

create table if not exists public.waiting_list_form (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  role text not null check (role in ('founder', 'investor', 'community', 'expert', 'partner', 'other')),
  country text not null,
  linkedin text,
  interest text check (char_length(interest) <= 800),
  consent boolean not null check (consent = true),
  created_at timestamptz not null default now()
);

alter table public.waiting_list_form enable row level security;

revoke all on table public.waiting_list_form from anon, authenticated;
grant insert on table public.waiting_list_form to anon, authenticated;
grant usage, select on sequence public.waiting_list_form_id_seq to anon, authenticated;

drop policy if exists "Allow public waiting-list submissions" on public.waiting_list_form;
create policy "Allow public waiting-list submissions"
on public.waiting_list_form
for insert
to anon, authenticated
with check (consent = true);
