"use client";

import { useState } from "react";
import { FounderDiligenceAiMessage } from "./FounderDiligenceAiMessage";

const PROMPTS = ["What should I answer first?", "What evidence is still missing?", "Assess my diligence readiness.", "Explain the current Term Sheet."];
export function FounderDiligenceAiPanel({ roomId, onClose }: { roomId: string; onClose: () => void }) {
  const [input, setInput] = useState(""); const [messages, setMessages] = useState<Array<{ role: "user" | "assistant"; content: string }>>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function ask(message: string) { const value = message.trim(); if (!value || busy) return; setInput(""); setError(""); setMessages((current) => [...current, { role: "user", content: value }]); setBusy(true); try { const response = await fetch(`/api/diligence/rooms/${roomId}/ai/chat`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ message: value, audience: "founder", mode: "general" }) }); const result = await response.json() as { answer?: string; error?: string }; if (!response.ok || !result.answer) throw new Error(result.error ?? "Unable to reach Kori AI."); setMessages((current) => [...current, { role: "assistant", content: result.answer ?? "" }]); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to reach Kori AI."); } finally { setBusy(false); } }
  return <aside className="dd-founder-ai-panel"><header><div><small>Founder Diligence Assistant</small><h2>Kori AI</h2></div><button type="button" onClick={onClose}>×</button></header><p className="notice">AI drafts can be incomplete. You review and submit every response.</p><div className="messages">{!messages.length ? <div className="suggestions">{PROMPTS.map((prompt) => <button type="button" key={prompt} onClick={() => setInput(prompt)}>{prompt}</button>)}</div> : null}{messages.map((message, index) => <FounderDiligenceAiMessage key={`${index}-${message.role}`} {...message} onCopy={(content) => void navigator.clipboard.writeText(content)} />)}{busy ? <p>Reviewing founder-visible diligence…</p> : null}{error ? <p role="alert">{error}</p> : null}</div><form onSubmit={(event) => { event.preventDefault(); void ask(input); }}><textarea value={input} onChange={(event) => setInput(event.target.value)} maxLength={4000} placeholder="Ask Kori AI" /><button type="submit" disabled={busy || !input.trim()}>Ask Kori AI</button></form></aside>;
}
