import type { ActivityRecord, MetricRecord } from "./shared";
import { fundManagerData } from "./fund-manager";

export const angelInvestorData = {
  metrics: [
    {
      labelKey: "invested",
      value: "$185K",
      detailKey: "investedDetail",
      tone: "gold",
    },
    {
      labelKey: "unreleased",
      value: "$62K",
      detailKey: "unreleasedDetail",
    },
    {
      labelKey: "activeDeals",
      value: "3",
      detailKey: "activeDealsDetail",
      tone: "teal",
    },
    {
      labelKey: "milestonesHit",
      value: "5/9",
      detailKey: "milestonesHitDetail",
    },
  ] satisfies MetricRecord[],
  activities: [
    {
      id: "milestoneApproved",
      textValues: { milestone: 2, spv: "SolarGrid Kenya SPV" },
      timeValues: { count: 2 },
      tone: "teal",
    },
    {
      id: "trancheReleased",
      textValues: { amount: "$25K", company: "EduBridge Ethiopia" },
      timeValues: { milestone: 1, count: 3 },
      tone: "gold",
    },
    {
      id: "newDeal",
      textValues: { company: "HealthLink South Africa" },
      timeValues: { count: 4 },
    },
  ] satisfies ActivityRecord[],
  allocation: [
    { name: "SolarGrid Kenya SPV", amount: "$100K", percentage: 54 },
    { name: "EduBridge Ethiopia SPV", amount: "$50K", percentage: 27 },
    { name: "AgriFlow Ghana SPV", amount: "$35K", percentage: 19 },
  ],
  deals: [
    {
      id: "healthLink",
      name: "HealthLink South Africa",
      target: "$400K",
      minimum: "$25K",
      instrument: "safe",
      investors: "0",
      committed: "$0",
      progress: 0,
      lead: "Adaeze Chukwu",
      open: true,
    },
    {
      id: "logiChain",
      name: "LogiChain Tanzania",
      target: "$250K",
      minimum: "$25K",
      instrument: "convertibleNote",
      investors: "2",
      committed: "$80K",
      progress: 32,
      lead: "Marcus Diallo",
      open: true,
    },
    {
      id: "agriFlow",
      name: "AgriFlow Ghana",
      target: "$350K",
      minimum: "$25K",
      instrument: "safe",
      investors: "6",
      committed: "$275K",
      progress: 79,
      lead: "Nana Asante",
      open: true,
    },
    {
      id: "solarGrid",
      name: "SolarGrid Kenya",
      target: "$500K",
      minimum: "$25K",
      instrument: "safe",
      investors: "8",
      committed: "$480K",
      progress: 96,
      lead: "Kofi Mensah",
      open: false,
    },
    {
      id: "eduBridge",
      name: "EduBridge Ethiopia",
      target: "$250K",
      minimum: "$25K",
      instrument: "equity",
      investors: "4",
      committed: "$250K",
      progress: 100,
      lead: "Amina Tadesse",
      open: false,
    },
  ],
  portfolio: [
    {
      name: "SolarGrid Kenya SPV",
      sector: "energy",
      country: "kenya",
      invested: "$100K",
      released: "$58K",
      milestones: "2/4",
      status: "active",
    },
    {
      name: "EduBridge Ethiopia SPV",
      sector: "edtech",
      country: "ethiopia",
      invested: "$50K",
      released: "$20K",
      milestones: "1/3",
      status: "active",
    },
    {
      name: "AgriFlow Ghana SPV",
      sector: "agritech",
      country: "ghana",
      invested: "$35K",
      released: "—",
      milestones: "0/4",
      status: "fundraising",
    },
  ],
  milestoneGroups: fundManagerData.milestoneGroups,
  transactions: [
    {
      date: "2025-04-18",
      spv: "SolarGrid Kenya SPV",
      type: "release",
      milestone: "solarPilot",
      amount: "+$26K",
      status: "confirmed",
      hash: "0x8fa2…91ce",
    },
    {
      date: "2025-04-03",
      spv: "EduBridge Ethiopia SPV",
      type: "release",
      milestone: "eduPlatform",
      amount: "+$20K",
      status: "confirmed",
      hash: "0x31bd…a710",
    },
    {
      date: "2025-03-22",
      spv: "AgriFlow Ghana SPV",
      type: "commitment",
      milestone: "escrowDeposit",
      amount: "$35K",
      status: "demo",
      hash: "0xc82e…f140",
    },
    {
      date: "2025-01-19",
      spv: "SolarGrid Kenya SPV",
      type: "release",
      milestone: "solarEntity",
      amount: "+$30K",
      status: "confirmed",
      hash: "0x11aa…923d",
    },
  ],
} as const;
